### ISSUE TITLE
Where is the product of experts?

### ISSUE THREAD

**Issue by ConanCui** [jzhou316/Unsupervised-Sentence-Summarization#3]
Hi, can you show me where is the operation to do the product of experts in the code?

**Comment by jzhou316** [comment]
Hi sorry didn't see this in time. Here is where the two probabilistic models are mixed https://github.com/jzhou316/Unsupervised-Sentence-Summarization/blob/ed0fb6266b5c6c8d03bcb16dd803eae2bbff0f94/uss/beam_search.py#L356.
